# -*- coding: utf-8 -*-
"""SB2527 Percolation 1-D, Phase Transition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tdthcpWNpXmtc3D0ayYjPbovh9xjP8Xt

# Phase Transition
Find the critical values of p using prior data, and plot them
"""

#This code approximates the position of the phase transition by finding the value of p for which the mean cluster size is maximised
#These values of p are the crtical values of the system for the given system size
k = 0
values = []
while k < len(chain_stats[0]):
 i = 0
 while i < len(chain_stats[0][k]['moments'][2]):
  if max(abs(chain_stats[0][k]['moments'][2])) == abs(chain_stats[0][k]['moments'][2][i]):
   values.append(round(chain_stats[0][k]['ps'][i],4))
  i += 1
 k +=1
print(values)