# -*- coding: utf-8 -*-
"""SB2527 Percolation 2-D Run.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QDFviVXgGjRfh7ROdFUM6ieCvYZuM11P
"""

#Runs the simulation and generates data
grid_ls, grid_ps_arrays, grid_stats = Canonical_Simulation(grid_runs = 40, grid_ls = [3, 10, 32, 100], grid_ps_arrays = 100)